# Site settings
title: chintan vora
description: my portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chintan Vora
user_description: Tell about yourself in short
user_title: Assistant Project Manager
email: vchintan6@gmail.com
twitter_username: chintanv_vora
github_username:  chintan-vora

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
